### ISSUE TITLE
What is the purpose of this Xblock?

### ISSUE THREAD

**Issue by sahilpatel1997** [proversity-org/genesys-xblock#2]
Hello,

I have a question regarding the purpose of this xblock and how can I use it in Open-Edx platform as I don't find any information and use about this Xblock. Also, have a question that how can I get/generate credentials to work with this xblock?

**Comment by lidijarad** [comment]
Hi there @sahilpatel1997, Genesys is an external paid-for psychometric testing service. If you have an account with Genesys (you will be able to retrieve an API token) then you will be able to use this Xblock to connect to the Genesys API and link to an external test, and to receive the results from the psychometric test.

**Comment by sahilpatel1997** [comment]
Oh!Thank you @lidijarad
